name = "pindex"
uuid = "8ad4ee32-087f-11e9-1bb2-8f020b060e7f"
authors = ["sejinahn2 <43711842+sejinahn2@users.noreply.github.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
